import {
  cloudEnabled, ensureSession, signIn, signInWithGoogle, clearSession,
  adminIsCurrent, getAdminDashboard, adminUpdatePlan, adminSetMerchantPlan,
} from './cloud.js'

const $=(s,e=document)=>e.querySelector(s), $$=(s,e=document)=>[...e.querySelectorAll(s)]
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))
const money=n=>Number(n||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})
const date=v=>v?new Date(v).toLocaleDateString('pt-BR'):'—'
const datetime=v=>v?new Date(v).toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short'}):'—'
const logo=()=>'<img src="/zaia-logo.svg" class="mgmt-logo" alt="ZAIA">'

let session=null,allowed=false,data=null,loading=true,authMessage='',tab='overview',modal=null,query=''

async function boot(){
  loading=true;render()
  if(!cloudEnabled()){authMessage='A gestão ZAIA precisa da conexão com o servidor.';loading=false;render();return}
  session=await ensureSession()
  if(!session){loading=false;render();return}
  try{allowed=await adminIsCurrent();if(allowed)data=await getAdminDashboard()}catch(error){authMessage=String(error.message||error)}
  loading=false;render()
}

function render(){
  const app=$('#app');if(!app)return
  if(loading){app.innerHTML='<main class="mgmt-loading">'+logo()+'<div class="loading-ring"></div><p>Carregando gestão ZAIA...</p></main>';return}
  if(!session){app.innerHTML=loginPage();bindLogin();return}
  if(!allowed){app.innerHTML='<main class="mgmt-denied">'+logo()+'<h1>Acesso restrito</h1><p>Esta área é exclusiva da administração da ZAIA.</p><a href="/" class="btn primary">Voltar para a ZAIA</a></main>';return}
  app.innerHTML='<div class="mgmt-shell">'+sidebar()+'<div class="mgmt-workspace">'+topbar()+'<main class="mgmt-content">'+content()+'</main></div></div>'+modalHtml()
  bind()
}
function loginPage(){return `<main class="mgmt-auth"><section class="mgmt-auth-card">${logo()}<span class="eyebrow">GESTÃO ZAIA</span><h1>Painel administrativo</h1><p>Planos, lojistas, assinaturas e visão financeira da plataforma.</p>${authMessage?`<div class="warning-box">${esc(authMessage)}</div>`:''}<button class="google-auth-btn" id="adminGoogle"><span class="google-g">G</span><span>Continuar com Google</span></button><div class="auth-divider"><span>ou</span></div><form id="adminLogin" class="form"><div class="field"><label>E-mail</label><input name="email" type="email" required></div><div class="field"><label>Senha</label><input name="password" type="password" required></div><button class="btn primary wide" type="submit">Entrar</button></form><a href="/" class="mgmt-back-link">Voltar para ZAIA</a></section></main>`}
function sidebar(){const items=[['overview','Visão geral'],['merchants','Lojistas'],['plans','Planos'],['finance','Financeiro']];return `<aside class="mgmt-sidebar"><div class="mgmt-brand">${logo()}<span>Gestão</span></div><nav>${items.map(([k,l])=>`<button data-tab="${k}" class="${tab===k?'active':''}">${l}</button>`).join('')}</nav><div class="mgmt-sidebar-foot"><a href="/">Abrir ZAIA</a><button id="adminLogout">Sair</button></div></aside>`}
function topbar(){return `<header class="mgmt-topbar"><div><span class="eyebrow">NETHANEL • ZAIA</span><strong>Painel gerencial</strong></div><div class="mgmt-admin-chip"><span>${esc((session?.user?.email||'A')[0].toUpperCase())}</span><b>Administrador</b></div></header>`}
function content(){return tab==='merchants'?merchantsPage():tab==='plans'?plansPage():tab==='finance'?financePage():overviewPage()}
function overviewPage(){const s=data?.summary||{},plans=data?.plans||[];return `<div class="mgmt-page-head"><span class="eyebrow">VISÃO GERAL</span><h1>ZAIA em números.</h1><p>Base ativa, conversão para PRO e visão financeira da plataforma.</p></div><section class="mgmt-kpis"><article><span>Lojistas ativos</span><strong>${s.active_merchants||0}</strong><small>Estabelecimentos ativos</small></article><article><span>Assinantes</span><strong>${s.subscribers||0}</strong><small>PRO com assinatura ativa</small></article><article><span>Em teste PRO</span><strong>${s.trials||0}</strong><small>Períodos de avaliação</small></article><article><span>MRR</span><strong>${money(s.projected_mrr)}</strong><small>Receita recorrente projetada</small></article></section><section class="mgmt-grid-two"><article class="card mgmt-card"><div class="section-head"><div><span class="eyebrow">PLANOS</span><h2>Distribuição da base</h2></div><button class="btn small ghost" data-tab-jump="plans">Gerenciar</button></div><div class="mgmt-plan-split">${plans.map(p=>`<div><span><b>${esc(p.name)}</b><small>${p.merchant_count} lojista${Number(p.merchant_count)===1?'':'s'}</small></span><strong>${p.code==='FREE'?'Grátis':money(p.monthly_price)+'/mês'}</strong></div>`).join('')}</div></article><article class="card mgmt-card"><div class="section-head"><div><span class="eyebrow">FINANCEIRO</span><h2>Plataforma</h2></div><button class="btn small ghost" data-tab-jump="finance">Detalhes</button></div><div class="mgmt-money-list"><div><span>Recebido no mês</span><strong>${money(s.collected_month)}</strong></div><div><span>Receita pendente</span><strong>${money(s.pending_revenue)}</strong></div><div><span>Volume dos lojistas</span><strong>${money(s.merchant_gmv_month)}</strong></div></div><p class="mgmt-note">Receita recebida ficará automática quando conectarmos o pagamento.</p></article></section>`}
function merchantsPage(){const merchants=(data?.merchants||[]).filter(m=>!query||m.name.toLowerCase().includes(query.toLowerCase()));return `<div class="mgmt-page-head row-head"><div><span class="eyebrow">LOJISTAS</span><h1>Base de estabelecimentos</h1><p>Plano, atividade, clientes e volume movimentado.</p></div><div class="mgmt-search"><input id="merchantSearch" value="${esc(query)}" placeholder="Buscar lojista"></div></div><div class="mgmt-table-wrap"><table class="mgmt-table"><thead><tr><th>Lojista</th><th>Plano</th><th>Status</th><th>Clientes</th><th>Agend. 30d</th><th>GMV mês</th><th>Atividade</th><th></th></tr></thead><tbody>${merchants.map(m=>`<tr><td><strong>${esc(m.name)}</strong><small>${esc(m.slug||'')}</small></td><td><span class="mgmt-plan-tag ${m.plan_code==='PRO'?'pro':''}">${m.plan_code}</span></td><td>${statusBadge(m.subscription_status)}</td><td>${m.clients}</td><td>${m.appointments_30d}</td><td>${money(m.gmv_month)}</td><td>${datetime(m.last_activity)}</td><td><button class="btn small ghost" data-merchant-edit="${m.id}">Gerenciar</button></td></tr>`).join('')||'<tr><td colspan="8">Nenhum lojista encontrado.</td></tr>'}</tbody></table></div>`}
function plansPage(){const plans=data?.plans||[];return `<div class="mgmt-page-head"><span class="eyebrow">PLANOS</span><h1>Preço sem mexer no código.</h1><p>Altere valores, teste gratuito, recursos e disponibilidade. A tela do lojista atualiza automaticamente.</p></div><section class="mgmt-plan-grid">${plans.map(p=>`<article class="mgmt-plan-card ${p.highlighted?'highlighted':''}"><div class="mgmt-plan-top"><div><span class="eyebrow">${p.code}</span><h2>${esc(p.name)}</h2><p>${esc(p.description||'')}</p></div><span class="pill ${p.active?'good':''}">${p.active?'Ativo':'Inativo'}</span></div><div class="mgmt-plan-price"><strong>${p.monthly_price>0?money(p.monthly_price):'Grátis'}</strong>${p.monthly_price>0?'<span>/mês</span>':''}</div>${p.annual_price>0?`<div class="mgmt-plan-annual">Anual: ${money(p.annual_price)}</div>`:''}<div class="mgmt-plan-stats"><span>${p.merchant_count} lojistas</span><span>${p.subscriber_count} assinantes</span><span>${p.trial_days} dias teste</span></div><button class="btn primary wide" data-plan-edit="${p.code}">Editar plano</button></article>`).join('')}</section>`}
function financePage(){const s=data?.summary||{},f=data?.finance||{},payments=f.payments||[];return `<div class="mgmt-page-head"><span class="eyebrow">FINANCEIRO DA PLATAFORMA</span><h1>Receita da ZAIA.</h1><p>Separada do financeiro dos lojistas.</p></div><section class="mgmt-kpis"><article><span>MRR projetado</span><strong>${money(s.projected_mrr)}</strong><small>Assinaturas ativas</small></article><article><span>ARR projetado</span><strong>${money(Number(s.projected_mrr||0)*12)}</strong><small>MRR × 12</small></article><article><span>Recebido no mês</span><strong>${money(s.collected_month)}</strong><small>Pagamentos confirmados</small></article><article><span>Pendente</span><strong>${money(s.pending_revenue)}</strong><small>Aguardando pagamento</small></article></section><article class="card mgmt-card" style="margin-top:14px"><div class="section-head"><div><span class="eyebrow">ÚLTIMOS PAGAMENTOS</span><h2>Movimentações de assinatura</h2></div></div>${payments.length?`<div class="mgmt-table-wrap"><table class="mgmt-table"><thead><tr><th>Lojista</th><th>Plano</th><th>Valor</th><th>Status</th><th>Pago em</th></tr></thead><tbody>${payments.map(p=>`<tr><td>${esc(p.merchant_name)}</td><td>${p.plan_code}</td><td>${money(p.amount)}</td><td>${statusBadge(p.status)}</td><td>${datetime(p.paid_at)}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty"><b>Ainda não há pagamentos.</b>Essa área começará a receber dados quando conectarmos o provedor de pagamento.</div>'}</article>`}
function statusBadge(v){const good=['ACTIVE','PAID'].includes(v),warn=['TRIAL','PENDING','PAST_DUE'].includes(v);return `<span class="pill ${good?'good':warn?'warn':''}">${esc(v||'—')}</span>`}
function modalHtml(){
  if(!modal)return ''
  const close='<button class="x" data-modal-close>×</button>'
  if(modal.type==='plan'){const p=(data?.plans||[]).find(x=>x.code===modal.code);if(!p)return '';return `<div class="modal-backdrop"><div class="modal mgmt-modal"><div class="modal-head"><div><span class="eyebrow">EDITAR PLANO</span><h3>${esc(p.name)}</h3></div>${close}</div><form id="planForm" class="form"><input type="hidden" name="code" value="${p.code}"><div class="field"><label>Nome</label><input name="name" value="${esc(p.name)}" required></div><div class="field"><label>Descrição</label><textarea name="description" rows="2">${esc(p.description||'')}</textarea></div><div class="row"><div class="field"><label>Mensal</label><input name="monthlyPrice" type="number" min="0" step="0.01" value="${p.monthly_price}"></div><div class="field"><label>Anual</label><input name="annualPrice" type="number" min="0" step="0.01" value="${p.annual_price}"></div></div><div class="field"><label>Dias de teste</label><input name="trialDays" type="number" min="0" max="90" value="${p.trial_days}"></div><div class="field"><label>Recursos <small>um por linha</small></label><textarea name="features" rows="7">${esc((p.features||[]).join('\n'))}</textarea></div><label class="toggle-row"><input type="checkbox" name="active" ${p.active?'checked':''}><span><strong>Plano ativo</strong></span></label><label class="toggle-row"><input type="checkbox" name="highlighted" ${p.highlighted?'checked':''}><span><strong>Destacar como recomendado</strong></span></label><button class="btn primary wide">Salvar alterações</button></form></div></div>`}
  if(modal.type==='merchant'){const m=(data?.merchants||[]).find(x=>x.id===modal.id);if(!m)return '';return `<div class="modal-backdrop"><div class="modal mgmt-modal"><div class="modal-head"><div><span class="eyebrow">LOJISTA</span><h3>${esc(m.name)}</h3></div>${close}</div><div class="mgmt-merchant-summary"><div><span>Plano atual</span><strong>${m.plan_code}</strong></div><div><span>Status</span><strong>${m.subscription_status}</strong></div><div><span>Clientes</span><strong>${m.clients}</strong></div><div><span>GMV mês</span><strong>${money(m.gmv_month)}</strong></div></div><form id="merchantPlanForm" class="form"><input type="hidden" name="id" value="${m.id}"><div class="field"><label>Plano</label><select name="planCode"><option value="FREE" ${m.plan_code==='FREE'?'selected':''}>ZAIA Free</option><option value="PRO" ${m.plan_code==='PRO'?'selected':''}>ZAIA Pro</option></select></div><div class="field"><label>Status</label><select name="status"><option value="FREE" ${m.subscription_status==='FREE'?'selected':''}>FREE</option><option value="TRIAL" ${m.subscription_status==='TRIAL'?'selected':''}>TRIAL</option><option value="ACTIVE" ${m.subscription_status==='ACTIVE'?'selected':''}>ACTIVE</option><option value="PAST_DUE" ${m.subscription_status==='PAST_DUE'?'selected':''}>PAST_DUE</option><option value="CANCELLED" ${m.subscription_status==='CANCELLED'?'selected':''}>CANCELLED</option></select></div><div class="field"><label>Cobrança</label><select name="cycle"><option value="MONTHLY" ${m.billing_cycle==='MONTHLY'?'selected':''}>Mensal</option><option value="ANNUAL" ${m.billing_cycle==='ANNUAL'?'selected':''}>Anual</option></select></div><button class="btn primary wide">Salvar plano do lojista</button></form></div></div>`}
  return ''
}
function bindLogin(){
  $('#adminGoogle')?.addEventListener('click',()=>{localStorage.setItem('zaia_after_google','/gestao');signInWithGoogle('https://nethanel-beauty.vercel.app/')})
  $('#adminLogin')?.addEventListener('submit',async e=>{e.preventDefault();const fd=Object.fromEntries(new FormData(e.currentTarget));try{await signIn(fd.email,fd.password);await boot()}catch(error){authMessage=String(error.message||error);render()}})
}
function bind(){
  $$('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;render()})
  $$('[data-tab-jump]').forEach(b=>b.onclick=()=>{tab=b.dataset.tabJump;render()})
  $('#adminLogout')?.addEventListener('click',()=>{clearSession();session=null;allowed=false;data=null;render()})
  $('#merchantSearch')?.addEventListener('input',e=>{query=e.target.value;render()})
  $$('[data-plan-edit]').forEach(b=>b.onclick=()=>{modal={type:'plan',code:b.dataset.planEdit};render()})
  $$('[data-merchant-edit]').forEach(b=>b.onclick=()=>{modal={type:'merchant',id:b.dataset.merchantEdit};render()})
  $$('[data-modal-close]').forEach(b=>b.onclick=()=>{modal=null;render()})
  $('#planForm')?.addEventListener('submit',async e=>{e.preventDefault();const fd=Object.fromEntries(new FormData(e.currentTarget)),btn=e.currentTarget.querySelector('button[type="submit"]');btn.disabled=true;btn.textContent='Salvando...';try{await adminUpdatePlan({code:fd.code,name:fd.name,description:fd.description,monthlyPrice:fd.monthlyPrice,annualPrice:fd.annualPrice,trialDays:fd.trialDays,active:e.currentTarget.elements.active.checked,highlighted:e.currentTarget.elements.highlighted.checked,features:String(fd.features||'').split('\n').map(x=>x.trim()).filter(Boolean)});data=await getAdminDashboard();modal=null;render()}catch(error){alert(String(error.message||error));btn.disabled=false;btn.textContent='Salvar alterações'}})
  $('#merchantPlanForm')?.addEventListener('submit',async e=>{e.preventDefault();const fd=Object.fromEntries(new FormData(e.currentTarget)),btn=e.currentTarget.querySelector('button[type="submit"]');btn.disabled=true;btn.textContent='Salvando...';try{await adminSetMerchantPlan(fd.id,fd.planCode,fd.status,fd.cycle);data=await getAdminDashboard();modal=null;render()}catch(error){alert(String(error.message||error));btn.disabled=false;btn.textContent='Salvar plano do lojista'}})
}
boot()
